[2025-10-05T03:18:49.889+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T03:18:49.912+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_analysis.load_records scheduled__2025-10-04T02:30:00+00:00 [queued]>
[2025-10-05T03:18:49.921+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_analysis.load_records scheduled__2025-10-04T02:30:00+00:00 [queued]>
[2025-10-05T03:18:49.921+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-05T03:18:49.929+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_records> on 2025-10-04 02:30:00+00:00
[2025-10-05T03:18:49.955+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=34468) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-05T03:18:49.956+0000] {standard_task_runner.py:72} INFO - Started process 34471 to run task
[2025-10-05T03:18:49.957+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Stock_analysis', 'load_records', 'scheduled__2025-10-04T02:30:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/Data226_Kruthika_V_HW5.py', '--cfg-path', '/tmp/tmp_724pszi']
[2025-10-05T03:18:49.959+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask load_records
[2025-10-05T03:18:49.999+0000] {task_command.py:467} INFO - Running <TaskInstance: Stock_analysis.load_records scheduled__2025-10-04T02:30:00+00:00 [running]> on host b99170a1b783
[2025-10-05T03:18:50.046+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_analysis' AIRFLOW_CTX_TASK_ID='load_records' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-04T02:30:00+00:00'
[2025-10-05T03:18:50.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T03:18:50.060+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-05T03:18:50.061+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-05T03:18:50.061+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-05T03:18:50.061+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-05T03:18:51.342+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-05T03:18:51.344+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-05T03:18:51.345+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-05T03:18:51.345+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-05T03:18:52.215+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-05T03:18:52.382+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-05T03:18:52.382+0000] {connection.py:788} INFO - closed
[2025-10-05T03:18:52.478+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-10-05T03:20:35.589+0000] {job.py:229} INFO - Heartbeat recovered after 84.11 seconds
[2025-10-05T03:21:11.058+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-05T03:21:11.062+0000] {connection.py:788} INFO - closed
[2025-10-05T03:21:11.119+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-10-05T03:21:11.214+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-05T03:21:11.295+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T03:21:11.297+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Stock_analysis, task_id=load_records, run_id=scheduled__2025-10-04T02:30:00+00:00, execution_date=20251004T023000, start_date=20251005T031849, end_date=20251005T032111
[2025-10-05T03:21:11.344+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T03:21:11.382+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T03:21:11.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
