[2025-10-03T06:35:25.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-03T06:35:25.590+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_analysis.count_records__1 manual__2025-10-03T06:31:28.040687+00:00 [queued]>
[2025-10-03T06:35:25.592+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_analysis.count_records__1 manual__2025-10-03T06:31:28.040687+00:00 [queued]>
[2025-10-03T06:35:25.592+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-03T06:35:25.595+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): count_records__1> on 2025-10-03 06:31:28.040687+00:00
[2025-10-03T06:35:25.599+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-03T06:35:25.599+0000] {standard_task_runner.py:72} INFO - Started process 8493 to run task
[2025-10-03T06:35:25.599+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Stock_analysis', 'count_records__1', 'manual__2025-10-03T06:31:28.040687+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/Data226_Kruthika_V_HW5.py', '--cfg-path', '/tmp/tmpivdm78wd']
[2025-10-03T06:35:25.600+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask count_records__1
[2025-10-03T06:35:25.615+0000] {task_command.py:467} INFO - Running <TaskInstance: Stock_analysis.count_records__1 manual__2025-10-03T06:31:28.040687+00:00 [running]> on host b99170a1b783
[2025-10-03T06:35:25.640+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_analysis' AIRFLOW_CTX_TASK_ID='count_records__1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T06:31:28.040687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-03T06:31:28.040687+00:00'
[2025-10-03T06:35:25.640+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-03T06:35:25.644+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-03T06:35:25.644+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-03T06:35:25.645+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-03T06:35:25.645+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-03T06:35:26.264+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-03T06:35:26.369+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-03T06:35:26.370+0000] {logging_mixin.py:190} INFO - Row count: 91
[2025-10-03T06:35:26.370+0000] {connection.py:788} INFO - closed
[2025-10-03T06:35:26.438+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-10-03T06:35:26.531+0000] {python.py:240} INFO - Done. Returned value was: 91
[2025-10-03T06:35:26.556+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-03T06:35:26.556+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Stock_analysis, task_id=count_records__1, run_id=manual__2025-10-03T06:31:28.040687+00:00, execution_date=20251003T063128, start_date=20251003T063525, end_date=20251003T063526
[2025-10-03T06:35:26.609+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-03T06:35:26.620+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T06:35:26.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
