[2025-10-07T02:30:06.097+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-07T02:30:06.102+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_analysis_Full_Refresh.count_records scheduled__2025-10-06T02:30:00+00:00 [queued]>
[2025-10-07T02:30:06.105+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_analysis_Full_Refresh.count_records scheduled__2025-10-06T02:30:00+00:00 [queued]>
[2025-10-07T02:30:06.105+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-07T02:30:06.108+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): count_records> on 2025-10-06 02:30:00+00:00
[2025-10-07T02:30:06.111+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=55192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-07T02:30:06.112+0000] {standard_task_runner.py:72} INFO - Started process 55195 to run task
[2025-10-07T02:30:06.112+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Stock_analysis_Full_Refresh', 'count_records', 'scheduled__2025-10-06T02:30:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/Data226_Kruthika_V_HW5.py', '--cfg-path', '/tmp/tmphlcq2jc3']
[2025-10-07T02:30:06.113+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask count_records
[2025-10-07T02:30:06.127+0000] {task_command.py:467} INFO - Running <TaskInstance: Stock_analysis_Full_Refresh.count_records scheduled__2025-10-06T02:30:00+00:00 [running]> on host b99170a1b783
[2025-10-07T02:30:06.152+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_analysis_Full_Refresh' AIRFLOW_CTX_TASK_ID='count_records' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T02:30:00+00:00'
[2025-10-07T02:30:06.152+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-07T02:30:06.156+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-07T02:30:06.156+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-07T02:30:06.157+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-07T02:30:06.157+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-07T02:30:06.785+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-07T02:30:06.902+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-07T02:30:06.903+0000] {logging_mixin.py:190} INFO - Row count in raw.NVDA_DATA: 90
[2025-10-07T02:30:06.903+0000] {connection.py:788} INFO - closed
[2025-10-07T02:30:06.977+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-10-07T02:30:07.049+0000] {python.py:240} INFO - Done. Returned value was: 90
[2025-10-07T02:30:07.079+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-07T02:30:07.080+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Stock_analysis_Full_Refresh, task_id=count_records, run_id=scheduled__2025-10-06T02:30:00+00:00, execution_date=20251006T023000, start_date=20251007T023006, end_date=20251007T023007
[2025-10-07T02:30:07.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-07T02:30:07.105+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-07T02:30:07.106+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
